export const trek = [
  {
    id: 1,
    imgSrc: "/flyimg/0724b7e62b342d120500c43090219125_1_11zon.webp",
    title: "Scenic Trails to Annapurna Sanctuary",
    oldPrice: 1800,
    newPrice: 1500,
    rating: "2.0",
    reviews: "234",
    location: "Nepal",
    duration: "21 Days",
    description:
      "Experience the beauty of nature with our expertly guided trek through stunning landscapes and cultural wonders.",
  },
  {
    id: 2,
    imgSrc:
      "https://admin.ntb.gov.np/image-cache/CSK_028____Pic_4-1635071361.jpg?p=main&s=9cb03bbbb4b91e50781774ea9887e924",
    title: "Classic Journey to Everest Foothills",
    oldPrice: 1800,
    newPrice: 1500,
    rating: "2.0",
    reviews: "234",
    location: "Nepal",
    duration: "2 Hours",
    description:
      "Experience the beauty of nature with our expertly guided trek through stunning landscapes and cultural wonders.",
  },
  {
    id: 3,
    imgSrc: "/flyimg/massif-Mount-Everest-Himalayas-Nepal_7_11zon.webp",
    title: "Annapurna Circuit Expedition",
    oldPrice: 1800,
    newPrice: 1500,
    rating: "2.0",
    reviews: "234",
    location: "Nepal",
    duration: "2 Hours",
    description:
      "Experience the beauty of nature with our expertly guided trek through stunning landscapes and cultural wonders.",
  },
  {
    id: 4,
    imgSrc: "/flyimg/massif-Mount-Everest-Himalayas-Nepal_7_11zon.webp",
    title: "Langtang Alpine Exploration",
    oldPrice: 1800,
    newPrice: 1500,
    rating: "2.0",
    reviews: "234",
    location: "Nepal",
    duration: "2 Hours",
    description:
      "Experience the beauty of nature with our expertly guided trek through stunning landscapes and cultural wonders.",
  },
  {
    id: 5,
    imgSrc: "/flyimg/annapurnabasecamp-_5_11zon.webp",
    title: "Adventure to Annapurna Base Camp",
    oldPrice: 2000,
    newPrice: 1650,
    rating: "4.5",
    reviews: "312",
    location: "Nepal",
    duration: "7 Days",
    description:
      "Trek to the stunning Annapurna Base Camp through terraced fields, lush forests, and traditional villages for a memorable Himalayan adventure.",
  },
  {
    id: 6,
    imgSrc: "/flyimg/lobuche-peak-climbing-banner_10_11zon.webp",
    title: "Lobuche Peak Ascent Expedition",
    oldPrice: 2500,
    newPrice: 2100,
    rating: "4.2",
    reviews: "178",
    location: "Nepal",
    duration: "10 Days",
    description:
      "Challenge yourself with a climb to Lobuche Peak and enjoy breathtaking panoramic views of Everest, Lhotse, and giants.",
  },
  {
    id: 7,
    imgSrc: "/flyimg/everest-base-camp-trek-2025_6_11zon.webp",
    title: "Everest Base Camp Adventure Trek",
    oldPrice: 2200,
    newPrice: 1899,
    rating: "4.8",
    reviews: "389",
    location: "Nepal",
    duration: "12 Days",
    description:
      "Embark on a legendary journey to the base of the world’s highest peak through awe-inspiring landscapes and Sherpa culture.",
  },
];
